src/actions/index.js
src/common/index.js
src/components/DepartmentSuccess/index.jsx
src/components/ErrorContainer/index.jsx
src/components/ErrorMessage/index.jsx
src/components/Main/index.jsx
src/components/PopulationSearchForm/index.jsx
src/components/StudentInfoCard/index.jsx
src/components/StudentSearch/index.jsx
src/components/TagListSelector/index.jsx
src/i18n/translations.json
src/reducers/errorReducer/index.js
src/styles/shared/layout.css

- fixed problems with fetch api TypeErrors
- fixed student and population statistics error handling

- added error handling to ui

---

src/actions/index.js
src/api/auth/index.js
src/api/common/index.js
src/api/index.js
src/common/index.js
src/components/NavigationBar/index.jsx
src/i18n/translations.json
src/reducers/errorReducer/index.js

prod: checks if token exists in localStorage before querying api,
if not => logs in and adds it to localStorage
if yes => adds token to headers. Logout removes token
- Added logout to Navbar
- 403 error removes also removes token from localStroage, to get rid of old tokens etc.
- Dev:
Same flow as in prod, except logs in as tktl as default
Also added UGLY dev controls, where user can select from list of users who he/she wants to be

- added token handling with following flows:

---

src/components/CreditAccumulationGraph/index.jsx
src/i18n/translations.json

repair CreditAccumulationGraph

---

src/common/index.js
src/components/CreditAccumulationGraph/index.jsx
src/components/CreditAccumulationGraphHighCharts/index.jsx
src/components/CreditGraphTooltip/index.jsx
src/components/EnableUsers/index.jsx
src/components/PopulationCourseStats/index.jsx
src/components/PopulationDetails/index.jsx
src/components/PopulationFilters/CourseParticipation.jsx
src/components/PopulationQueryCard/index.jsx
src/components/PopulationSearchForm/index.jsx
src/components/PopulationSearchHistory/index.jsx
src/components/PopulationStudents/index.jsx
src/components/StudentDetails/index.jsx
src/components/StudentInfoCard/index.jsx
src/populationFilters/index.js
src/selectors/populationSearchForm.js
superbara_tests/tests/components/query_population_statistics.rb
superbara_tests/tests/navbar_test.rb
superbara_tests/tests/population_statistics.rb

- Copy student email addresses to clipboard
- Handle localised objects instead of strings
- Updated API calls to send correct params to latest backend

Update frontend to work with data returned by the latest version of the backend

---

src/components/CoursePassRateChart/index.jsx
src/components/CourseStatistics/index.jsx
src/components/PopulationCourseStats/index.jsx
src/components/PopulationDetails/index.jsx
src/components/PopulationFilters/CreditsAtLeast.jsx
src/components/PopulationFilters/CreditsLessThan.jsx
src/components/PopulationFilters/DisciplineTypes.jsx
src/components/PopulationFilters/EnrollmentStatus.jsx
src/components/PopulationFilters/SexFilter.jsx
src/components/PopulationFilters/StartingThisSemester.jsx
src/components/PopulationFilters/TransferFilter.jsx
src/components/PopulationFilters/index.jsx
src/components/StudentDetails/index.jsx
src/components/StudyrightStatistics/index.jsx
src/i18n/translations.json
src/populationFilters/index.js
src/redux/courses.js
src/selectors/courses.js
superbara_tests/tests/course_statistics.rb
superbara_tests/tests/population_statistics.rb

- Course distribution graph
- Better tests
- new student statistics studyrights table
- Filtering by discipline and type
- Filter by semester enrollments
- Filter by study programme transfers

Million new features

---

src/components/EnableUsers/index.jsx
src/constants/index.js
src/redux/users.js

Initial improvements to users page for admins. 
- New `/users/:id` page for users
- Move studyright access editing to user page
- Change users list layout

Users page improvements Part 1. 

---

.babelrc
package-lock.json
package.json
src/components/CreditAccumulationGraphHighCharts/index.jsx
src/components/PopulationCourses/index.jsx
src/components/PopulationDetails/index.jsx
src/components/PopulationFilters/ExtentGraduated.jsx
src/components/PopulationSearchForm/index.jsx
src/populationFilters/index.js

-  Re-written ExtentGraduated Filter 
-  Added some default filters for all populations.
-  Removed all kludges and legacy bullshit from Highcharts credit accumulation graph.
-  Updated react-hot-loader

Extent graduated rewrite and added as default filter

---

src/components/StudyProgramme/ProductivityTable/index.jsx
src/components/StudyProgramme/ThroughputTable/index.jsx
src/components/StudyProgramme/index.jsx

studyprogramme page tables update

---

run.sh
scripts.sh
services/backend/oodikone2-backend/src/database/connection.js
services/backend/oodikone2-backend/src/database/migrations_kone/20190606_01_create_tags.js
services/backend/oodikone2-backend/src/database/migrations_kone/20190606_02_create_student_tags.js
services/backend/shared/models/index.js
services/oodikone2-frontend/src/components/PopulationStudents/index.jsx
services/oodikone2-frontend/src/components/StudyProgramme/StudyProgrammeSelector/index.jsx

merge Trunk

---

services/backend/oodikone2-backend/src/services/populations.js
services/oodikone2-frontend/src/components/PopulationSearchForm/index.jsx

https://github.com/UniversityOfHelsinkiCS/oodikone/issues/1186

Population advanced settings bug fix

---

services/backend/oodikone2-backend/src/routes/population.js
services/oodikone2-frontend/src/apiConnection/index.js
services/oodikone2-frontend/src/constants/index.js

Backend bug fix and sentry improvement (or just more spam, remains to be seen)

---

cypress/integration/Teachers.js
docker-compose.yml
services/backend/shared/migrations/20190806_00_transfers_delete_on_studyright_delete.js
services/backend/shared/migrations_kone/20190706_01_fix_sequence_out_of_sync.js
services/oodikone2-frontend/src/components/TeacherDetails/CoursesTab.jsx

there can never be enough tests

fixed teacher borking and added tests and refactored navbar

---

cypress/integration/Users.js
services/oodikone2-frontend/src/components/EnableUsers/index.jsx
services/oodikone2-frontend/src/components/PopulationCourseStats/index.jsx
services/oodikone2-frontend/src/components/PopulationSearchForm/index.jsx
services/oodikone2-frontend/src/components/UserPage/EmailNotification.jsx
services/oodikone2-frontend/src/components/UserPage/index.jsx

Move user list send mail button to user details page

---

services/backend/oodikone2-backend/src/events.js
services/backend/oodikone2-backend/src/routes/elementdetails.js
services/backend/oodikone2-backend/src/routes/population.js
services/backend/oodikone2-backend/src/routes/students.js
services/backend/oodikone2-backend/src/services/populations.js
services/backend/oodikone2-backend/src/services/studytrack.js
services/oodikone2-frontend/src/components/StudentDetails/index.jsx
services/oodikone2-frontend/src/components/StudyProgramme/Overview/index.jsx
services/oodikone2-frontend/src/components/StudyProgramme/ProductivityTable/index.jsx
services/oodikone2-frontend/src/components/StudyProgramme/ProductivityTable/productivityTable.css
services/oodikone2-frontend/src/components/StudyProgramme/Tags/index.jsx
services/oodikone2-frontend/src/components/StudyProgramme/ThroughputTable/index.jsx
services/oodikone2-frontend/src/components/TagStudent/index.jsx

Show "not applicable" for old programmes credits, show data 10 years back actually this time

---

services/backend/oodikone2-backend/src/services/populations.js
services/backend/oodikone2-backend/src/services/studyrights.js
services/oodikone2-frontend/src/components/CreditAccumulationGraphHighCharts/index.jsx
services/oodikone2-frontend/src/components/PopulationFilters/TransferFilter.jsx
services/oodikone2-frontend/src/components/Postman/index.jsx
services/oodikone2-frontend/src/components/StudentDetails/index.jsx
services/oodikone2-frontend/src/components/StudyProgramme/ThroughputTable/index.jsx

also fix single student graph errors

Fix certain populations year searches returning zero students

---

services/backend/oodikone2-backend/src/routes.js
services/backend/oodikone2-backend/src/routes/population.js
services/backend/oodikone2-backend/src/services/studyrights.js
services/oodikone2-frontend/src/components/CustomPopulation/index.jsx
services/oodikone2-frontend/src/components/StudyProgramme/PresentStudents/index.jsx

Added auth checking so that user can create a custom population from only students that they have rights for

Released custom populations to everyone

---

services/backend/oodikone2-backend/src/events.js
services/backend/oodikone2-backend/src/routes/elementdetails.js
services/backend/oodikone2-backend/src/services/analyticsService.js
services/backend/oodikone2-backend/src/services/studyrights.js
services/backend/oodikone2-backend/src/util/index.js
services/oodikone2-analytics/index.js
services/oodikone2-analytics/src/database/migrations/24191113_00_add_non_graduated_students.js
services/oodikone2-analytics/src/models/index.js
services/oodikone2-frontend/src/components/StudyProgramme/PresentStudents/index.jsx
services/oodikone2-frontend/src/components/StudyProgramme/index.jsx

Moved present student stats of old programmes to analytics service instead of recalculating them on every request

Moved present students stats to analytics service

---

docker-compose.yml
services/oodikone2-frontend/src/components/ErrorBoundary/index.jsx
services/oodikone2-frontend/src/components/Main/index.jsx
services/oodikone2-frontend/src/components/Routes/index.jsx
services/oodikone2-frontend/src/components/StudyProgramme/PresentStudents/YearAccordion.jsx
services/oodikone2-frontend/src/components/StudyProgramme/PresentStudents/index.jsx

also send analytics event when user is being mocked so we can distinguish them in the dashboard

Add 404 redirect to main page, set matomo user id earlier + total tab to present studs

---

services/updater_api/doo_api_database_updater/oodi_data_mapper.js

I see miracles all around me
Stop and look around, it's all astounding
Water, fire, air and dirt
Fucking updater, how does it work?

I don't wanna talk to a scientist

---

services/backend/oodikone2-backend/package-lock.json
services/backend/oodikone2-backend/package.json
services/backend/oodikone2-backend/src/app.js
services/backend/oodikone2-backend/src/middleware/sentryUserId.js
services/backend/oodikone2-backend/src/routes/population.js
services/backend/oodikone2-backend/src/routes/tsaAnalytics.js

Raven was deprecated long ago.

Update backend sentry to use @sentry/node

---

docker-compose.yml
docker/docker-compose.dev.yml
scripts/exec_command_for_services.sh
services/oodikone2-frontend/src/common/hooks.js
services/oodikone2-frontend/src/components/PopulationCourseStats/index.jsx
services/oodikone2-frontend/src/components/PopulationDetails/index.jsx
services/oodikone2-frontend/src/components/PopulationStudents/index.jsx
services/oodikone2-frontend/src/components/StudentNameVisibilityToggle/index.jsx
services/sis-updater/.dockerignore
services/sis-updater/.eslintrc.json
services/sis-updater/.gitignore
services/sis-updater/.prettierrc
services/sis-updater/Dockerfile
services/sis-updater/package-lock.json
services/sis-updater/package.json
services/sis-updater/src/index.js

Finish population details analytics

---

scripts/populate-db.sh
services/backend/shared/migrations/20200218_00_add_admin_view_funcs.js
services/oodikone2-frontend/src/apiConnection/index.js
services/oodikone2-frontend/src/common/index.js
services/oodikone2-frontend/src/components/NavigationBar/index.jsx
services/sis-updater-scheduler/Dockerfile
services/sis-updater-worker/src/db/migrations/20200219_00_add_column_abbreviatedname_to_students.js
services/sis-updater-worker/src/db/models/student.js
services/sis-updater-worker/src/updater/index.js

can't add the functions as temporary functions because production uses a
replica DB.

Add SQL functions in migration, not as temps

---

services/backend/oodikone2-backend/src/services/populations.js
services/backend/oodikone2-backend/src/services/studytrack.js
services/oodikone2-analytics/index.js
services/oodikone2-frontend/src/components/StudyProgramme/StudyTrackOverview/index.jsx
services/oodikone2-frontend/src/components/StudyProgramme/index.jsx

still admin only, need to test in prod

studytrack overview

---

.gitignore
services/oodikone2-frontend/src/components/PopulationDetails/CourseQuartiles.jsx
services/oodikone2-frontend/src/components/PopulationDetails/CreditGainStats/CreditsGainedTab.jsx
services/oodikone2-frontend/src/components/PopulationDetails/CreditGainStats/StatisticsTab.jsx
services/oodikone2-frontend/src/components/PopulationDetails/CreditGainStats/index.jsx
services/oodikone2-frontend/src/components/PopulationDetails/NewPopDetails.jsx
services/oodikone2-frontend/src/components/PopulationDetails/index.jsx
services/oodikone2-frontend/src/components/PopulationQueryCard/index.jsx
services/oodikone2-frontend/src/components/StudentDetails/index.jsx

Credit gain stats table is now more sensible. Maybe, or at least in my dreams.

Fix Haba's complaint

---

package-lock.json
package.json

Dustin Johnson will win, mark my words.

New week, new PR

---

cypress/integration/Course_population.js
cypress/integration/Course_statistics.js
cypress/integration/Population_statistics.js
package.json
scripts/grep_only.sh
services/oodikone2-frontend/src/common/markdown/populationStatistics/coursesOfPopulation.info.md
services/oodikone2-frontend/src/components/CourseStatistics/SearchForm/index.jsx
services/oodikone2-frontend/src/components/PopulationCourseStats/index.jsx
services/oodikone2-frontend/src/components/PopulationCourseStats/populationCourseStats.css
services/oodikone2-frontend/src/components/PopulationSearch/PopulationSearchForm.jsx
services/oodikone2-frontend/src/components/StudyProgramme/BachelorsTable/index.jsx
services/oodikone2-frontend/src/components/StudyProgramme/Overview/index.jsx
services/oodikone2-frontend/src/components/StudyProgramme/ProductivityTable/index.jsx
services/oodikone2-frontend/src/redux/studyProgrammeBachelors.js

* Fix #2338 UX issue
* Remove admin toggle form study programme options table in programme overview
* Partly fix #2322 
Tuesday night madness:
* Fix #1922 UX issue
* Fix #2367

Friday night madness

---

services/oodikone2-frontend/src/components/CoursePopulation/index.jsx
services/oodikone2-frontend/src/components/CourseStatistics/FacultyLevelStatistics/index.jsx
services/oodikone2-frontend/src/components/CourseStatistics/ResultTabs/Panes/Tables/grades.jsx
services/oodikone2-frontend/src/components/CourseStatistics/ResultTabs/Panes/distribution.jsx
services/oodikone2-frontend/src/components/CourseStatistics/ResultTabs/Panes/util.js
services/oodikone2-frontend/src/components/PopulationDetails/CreditGainStats/CreditsGainedTab.jsx

At least mandatory Swedish courses includes HT and TT grades, which caused course statistics to explode. Not nice demo for head of Kielikeskus.

Hotfix HT and TT grades for Kielikeskusjory

---

cypress/integration/Population_statistics.js
services/backend/oodikone2-backend/src/services/populations.js
services/oodikone2-frontend/src/common/index.js
services/oodikone2-frontend/src/components/CustomPopulation/UnihowDataExport.jsx
services/oodikone2-frontend/src/components/CustomPopulation/index.jsx
services/oodikone2-frontend/src/components/FilterTray/FilterSets.jsx
services/oodikone2-frontend/src/components/FilterTray/filters/Date.jsx
services/oodikone2-frontend/src/components/FilterTray/filters/Gender.jsx
services/oodikone2-frontend/src/components/FilterTray/filters/GraduatedFromProgramme.jsx
services/oodikone2-frontend/src/components/FilterTray/useFilters.jsx
services/oodikone2-frontend/src/components/PopulationCourseStats/PassFail/index.jsx
services/oodikone2-frontend/src/components/PopulationDetails/index.jsx
services/oodikone2-frontend/src/components/PopulationStatistics/DataExport.jsx
services/oodikone2-frontend/src/components/PopulationStatistics/index.jsx
services/oodikone2-frontend/src/components/PopulationStudents/index.jsx

Unihow data export

---

.circleci/config.yml
services/backend/oodikone2-backend/src/app.js
services/oodikone2-frontend/src/app.jsx

Update Sentry conf

---

cypress/integration/Course_statistics.js
services/oodikone2-frontend/src/components/AutoSubmitSearchInput/index.jsx
services/oodikone2-frontend/src/components/CourseStatistics/ResultTabs/Panes/Tables/attempts.jsx
services/oodikone2-frontend/src/components/CourseStatistics/ResultTabs/Panes/tables.jsx
services/oodikone2-frontend/src/components/CourseStatistics/ResultTabs/index.jsx
services/oodikone2-frontend/src/components/CourseStatistics/SingleCourseStats/countStatistics.js
services/oodikone2-frontend/src/components/CourseStatistics/SingleCourseStats/countTotalStats.js
services/oodikone2-frontend/src/components/CourseStatistics/SingleCourseStats/index.jsx

- Grades & Attempts -table now should match each other
- Attempts-student -toggle allows switching back now
- Fixes clearAllTimeouts -warning from console
- Adds totals for "after retry"-columns in student table, since they were missing.

Fixes to stats in Course Statistics

---

cypress/integration/Course_statistics.js
cypress/integration/Users.js
services/backend/oodikone2-backend/src/sisoodi_diff/students/compareCourses.js
services/backend/oodikone2-backend/src/sisoodi_diff/students/compareCoursesPairwise.js
services/backend/oodikone2-backend/src/sisoodi_diff/students/compareStudyModules.js
services/backend/oodikone2-backend/src/sisoodi_diff/students/getStudentNumbers.js
services/backend/oodikone2-backend/src/sisoodi_diff/students/index.js
services/backend/oodikone2-backend/src/sisoodi_diff/students/matchExactlyOneCourse.js
services/oodikone2-frontend/src/components/StudentStatistics/StudentInfoCard/index.jsx
services/oodikone2-frontend/src/components/UserPage/AccessGroups.jsx
services/oodikone2-frontend/src/components/UserPage/AccessRights.jsx
services/oodikone2-frontend/src/components/UserPage/index.jsx

Fixes and comments and yeah

---

services/backend/oodikone2-backend/src/servicesV2/studyprogramme.js

They were studentStudentnumber after all in the studyrights-table

Revert changing studentStudentnumber to student_studentnumber

---

services/userservice/src/database/migrations/20210818_00_add_new_special_programmes_to_faculties.js

Lääkis & kasvis special koulutukset incoming

Add some new special programmes for users with faculty rights

---

services/frontend/src/common/index.js
services/frontend/src/components/PopulationStudents/StudentTable/GeneralTab/GeneralTab.jsx
services/frontend/src/components/PopulationStudents/StudentTable/GeneralTab/columnHelpers/createMaps.js
services/frontend/src/components/PopulationStudents/StudentTable/GeneralTab/columnHelpers/studyProgramme.jsx
services/frontend/src/components/PopulationStudents/index.jsx

This should fix the broken dates. Pls test on Firefox and compare to production.
http://localhost:3000/populations?months=80&semesters=FALL&semesters=SPRING&studyRights={%22programme%22%3A%22KH70_004%22}&year=All&years=2017&years=2018&years=2019&years=2020&years=2021&years=2022&years=2023
http://oodikone.helsinki.fi/populations?months=80&semesters=FALL&semesters=SPRING&studyRights={%22programme%22%3A%22KH70_004%22}&year=All&years=2017&years=2018&years=2019&years=2020&years=2021&years=2022&years=2023

[Class statistics] Fix broken dates on Firefox

---

docker-compose.fd.yml

Created own docker compose file for funidata to run local dev enviroment

Created own docker compose file for funidata to run local dev enviroment

---

services/backend/config/facultyCodes.js
services/backend/src/services/organisations.js

Moved facultyCodes list to separate file for future configurability (possibly with a bind mount or something on our end)

[Backend] Extract facultyCodes to separate file

---

docker-compose.fd.yml
services/backend/config/organisationConstants.js
services/backend/src/routes/university.js
services/backend/src/services/organisations.js
updater/sis-updater-worker/src/config.js
updater/sis-updater-worker/src/updater/updateMeta.js
updater/sis-updater-worker/src/updater/updateStudents/attainments.js

Renamed `facultyCodes` to `organisationConstants`. Added new env variable `ROOT_ORG_ID` to overwrite universityOrgId default value will be same `hy-university-root-id`

[Backend][Updater] Renamed facultyCodes to organisationConstants and moved universityOrgId there

---

updater/sis-updater-worker/src/updater/shared.js

Added fallback to abbreviation in function initGradeScaleIdToGradeIdsToGrades

[Updater] Added fallback to abbreviation in function initGradeScaleIdToGradeIdsToGrades

---

services/backend/src/database/migrations_user/20190925_01_init_db_schema.js
updater/sis-updater-scheduler/src/db/connection.js
updater/sis-updater-worker/src/db/connection.js

There were some issues getting connections to AWS RDS hosted postgres with self signed certificates due to the knex default configurations, so tried to alleviate some of them.
The defaults for this changed somewhere around 2020 : 
https://node-postgres.com/announcements#2020-02-25
Also cleaned up some migration files that were doing things that were seemingly not that relevant, that were also causing some grey hairs in configuring database in RDS.

[Updater][Backend] AWS RDS compatibility

---

docker-compose.fd.yml

- Edited backend and frontend volumes in fd docker compose file
- Renamed SERVICE_PROVIDER to REACT_APP_SERVICE_PROVIDER

[FD compose] Edited backend and frontend volumes. Added also REACT_APP_SERVICE_PROVIDER env variable to frontend.

---

updater/sis-updater-worker/src/updater/shared.js

Added null check fallback to abbreviation in initGradeScaleIdToGradeIdsToGrades

[Updater] Added null check fallback to abbreviation in initGradeScaleIdToGradeIdsToGrades

---

services/backend/src/services/userService.ts

Renamed programmeRights to detailedProgrammeRights in fdGetUser

[Backend] Renamed programmeRights to detailedProgrammeRights in fdGetUser

---

services/frontend/src/components/Frontpage/index.jsx
services/frontend/src/components/NavigationBar/index.jsx
services/frontend/src/components/Routes/index.jsx

- Added conditional renders based on serviceProvider to FrontPage and NavigationBar components
- Added check to routes based on serviceProvider

[FrontPage][NavigationBar] Added conditional renders based on serviceProvider to FrontPage and NavigationBar components

---

services/backend/Dockerfile
services/backend/src/database/connection.ts

With part of the code being in TypeScript, we end up having a lot of dependencies that aren't really needed to run the application in production. Let's see if we can make a multi-stage build

[Backend] Multi-stage build to make final Docker image smaller

---

docker-compose.fd.yml
services/backend/src/util/logger.js
updater/sis-updater-scheduler/src/config.js
updater/sis-updater-scheduler/src/utils/logger.js
updater/sis-updater-worker/src/config.js
updater/sis-updater-worker/src/utils/logger.js

Fd don't want no winston gelf transporter.
https://funidata.atlassian.net/browse/OOD-13

OOD-13: no winston gelf for fd

---

docker-compose.fd.yml

Added env variable `ROOT_ORG_ID` to backend in fd compose

[FD compose] Added ROOT_ORG_ID to backend as well

---

services/backend/src/services/faculty/facultyThesisWriters.ts

We have in our test data some programme_modules which code is null so needed to add undefined check for thesisStats in facultyThesisWriters

[Backend] Added undefined check for thesisStats in facultyThesisWriters

---

services/frontend/src/components/FacultyStatistics/InteractiveDataView/ExpandableRow.jsx

Added optional chaining to function `roundValue`

[FacultyStatistics] Added optional chaining to function roundValue

---

.github/workflows/lint.yaml
.github/workflows/pull_request.yaml
.github/workflows/test.yaml

Let's reduce copy-paste and extract linting as a reusable workflow file.

Create a separate workflow for linting

---

services/backend/src/services/curriculumPeriods.ts
services/backend/src/services/faculty/faculty.ts
services/frontend/src/components/FacultyStatistics/FacultyProgrammeOverview/index.jsx

[Backend] Created curriculumPeriods service and refactored getDegreeProgrammesOfOrganization to use CurriculumPeriods instead of curriculumPeriodIdToYearCode way
[FacultyProgrammeOverview] Added creditCounts keys length check in function calculateStats

[Backend][Frontend] Replaced curriculumPeriodIdToYearCode with curriculumPeriods

---

updater/sis-updater-worker/src/updater/mapper.js
updater/sis-updater-worker/src/updater/updateMeta.js
updater/sis-updater-worker/src/updater/updateProgrammeModules/updateProgrammeModules.js

https://funidata.atlassian.net/browse/OOD-63

OOD-63: [updater] some added error handling and a null check

---

services/backend/src/routes/courses.ts
services/backend/src/services/courses/index.ts

As this problem only occurs in a client demo environment, and not, e.g., while running Oodikone locally, we need more specific logs to see why this route ends up timeouting instead of returning a response.

OOD-66: added debugging logging to pin point courses stats problem

---

cypress/e2e/Users.js
services/backend/src/routes/changelog.ts
services/frontend/src/components/material/Footer/index.tsx
services/frontend/src/components/material/NavigationBar/NavigationButton.tsx
services/frontend/src/components/material/NavigationBar/NavigationDivider.tsx
services/frontend/src/components/material/NavigationBar/OodikoneLogo.tsx
services/frontend/src/components/material/NavigationBar/UserButton/index.tsx
services/frontend/src/components/material/NavigationBar/index.tsx
services/frontend/src/pages/Changelog/ReleaseCard.tsx
services/shared/types/release.ts

Let's switch the navigation bar to a [Tabs](https://mui.com/material-ui/react-tabs) based layout.

Responsive navigation bar

---

services/frontend/src/pages/Users/UserPage/index.tsx

Added service provider check to UsersPage IamGroupsCard

[UserPage] Added service provider check to show IamGroupsCard

---

cypress/e2e/Population_statistics.js
services/backend/src/routes/population.ts
services/backend/src/services/courses/courseStatsCounter.ts
services/backend/src/services/populations/bottlenecksOf.ts
services/backend/src/services/populations/getStudentsIncludeCoursesBetween.ts
services/backend/src/services/populations/optimizedStatisticsOf.ts
services/backend/src/services/populations/shared.ts
services/backend/src/services/populations/studentNumbersWithAllElements.ts
services/backend/src/services/statMerger.ts
services/backend/src/services/students.ts
services/backend/src/util/index.ts
services/frontend/src/components/CustomOpenUniPopulation/CustomOpenUniSearch.jsx
services/frontend/src/components/FilterView/filters/studentNumber.jsx
services/frontend/src/components/PopulationDetails/CurriculumPicker.jsx
services/frontend/src/components/PopulationSearch/PopulationSearchForm.jsx
services/frontend/src/components/SortableTable/filters/defaultFilter.jsx
services/frontend/src/redux/populationCourses.js
services/frontend/src/redux/populationSelectedStudentCourses.js
services/frontend/src/redux/studyGuidanceGroups.js
services/shared/util/index.ts

Reverts UniversityOfHelsinkiCS/oodikone#4764

Revert "Populus optimus"

---

services/frontend/src/components/material/PopulationLink.tsx
services/frontend/src/pages/StudyProgramme/TagsTab/TagsSection/TagItem/index.tsx

This component contains a lot of copy-pasted code. Instead, let's construct the url from parts based on which params are provided.

[PopulationLink] Refactor to eliminate copy-paste

---

cypress/e2e/Study_programme_overview.js
services/frontend/src/components/material/PopulationLink.tsx
services/frontend/src/pages/StudyProgramme/StudyTracksAndClassStatisticsTab/StudyTrackDataTable/index.tsx
services/frontend/src/pages/StudyProgramme/StudyTracksAndClassStatisticsTab/YearSelector.tsx
services/frontend/src/pages/StudyProgramme/StudyTracksAndClassStatisticsTab/index.tsx
services/frontend/src/util/populationLink.ts

Adding a new slider for selecting a subset of years.

[Study programme overview] Add an option to select a subset of years

---

services/frontend/public/frontend-config.json
services/frontend/src/components/common/SisuLinkItem.tsx
services/frontend/src/components/material/StudentInfoItem.tsx
services/frontend/src/pages/Students/StudentDetails/StudentInfoCard.tsx

If your first shot don't succeed, you  dust yourself off and try again :smiling_face_with_tear: 
https://funidata.atlassian.net/browse/OOD-90

[FRONTEND] OOD-90: fetching frontend config from json
